#ifndef header_h
#define header_h

String file1=
"<!DOCTYPE html>\r\n"
"<head>\r\n"
"<title>Roboterhand MANU</title>\r\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">"
"<style>"
"button {"
  "background-color: #990033;"
  "border: none;"
  "color: white;"
  "padding: 7px 15px;"
  "text-align: center;"
  "cursor: pointer;"
"}"
".toggle label {"
  "position: relative;"
  "display: inline-block;"
  "width: 10em;"
  "height: 3.5em;"
"}"
".toggle input {"
  "display: none;"
"}"
".toggle .slider {"
  "position: absolute;"
  "cursor: pointer;"
  "top: 1.5em;"
  "left: 2em;"
  "width: 4em;"
  "height: 2em;"
  "background-color: #c32e04;"
  "transition: all .3s ease-in-out;"
  "border-radius: 1em;"
"}"
".toggle .slider:before {" 
  "position: absolute;"
  "content: \"\";"
  "height: 1.6em;"
  "width: 1.6em;"
  "left: 0.2em;"
  "bottom: 0.2em;"
  "background-color: white;"
  "border-radius: 50%;"
  "transition: all .3s ease-in-out;"
"}"
".toggle input:checked + .slider {"
  "background-color: #5a9900;"
"}"
".toggle input:focus + .slider {"
  "background-color: pink;"
  "box-shadow: 0 0 1px #5a9900;"
"}"
".toggle input:checked + .slider:before {"
  "-webkit-transform: translateX(1.9em); "
  "-ms-transform: translateX(1.9em);"
  "transform: translateX(1.9em);"
"}"
"input[type=range] {"
    /*removes default webkit styles*/
    "-webkit-appearance: none;"
    
    /*fix for FF unable to apply focus style bug */
    "border: none;"
    
    /*required for proper track sizing in FF*/
    "width: 300px;"
"}"
"input[type=range]::-webkit-slider-runnable-track {"
    "width: 300px;"
    "height: 10px;"
    "background: #a8a8a8;"
    "border: none;"
    "border-radius: 3px;"
"}"
"input[type=range]::-webkit-slider-thumb {"
    "-webkit-appearance: none;"
    "border: none;"
    "height: 16px;"
    "width: 30px;"
    "border-radius: 30%;"
    "background: #990033;"
    "margin-top: -4px;"
"}"
"input[type=range]:focus {"
    "outline: none;"
"}"
"input[type=range]:focus::-webkit-slider-runnable-track {"
    "background: #a2a2a2;"
"}"
"input[type=range]::-moz-range-track {"
    "width: 300px;"
    "height: 5px;"
    "background: #a8a8a8;"
    "border: none;"
    "border-radius: 3px;"
"}"
"input[type=range]::-moz-range-thumb {"
    "border: none;"
    "height: 16px;"
    "width: 30px;"
    "border-radius: 50%;"
    "background: #990033;"
"}"
/*hide the outline behind the border*/
"input[type=range]:-moz-focusring{"
    "outline: 1px solid white;"
    "outline-offset: -1px;"
"}"
"input[type=range]::-ms-track {"
    "width: 300px;"
    "height: 10px;"
    
    /*remove bg colour from the track, we'll use ms-fill-lower and ms-fill-upper instead */
    "background: transparent;"
    
    /*leave room for the larger thumb to overflow with a transparent border */
    "border-color: transparent;"
    "border-width: 6px 0;"

    /*remove default tick marks*/
    "color: transparent;"
"}"
"input[type=range]::-ms-fill-lower {"
    "background: #a8a8a8;"
    "border-radius: 10px;"
"}"
"input[type=range]::-ms-fill-upper {"
    "background: #a8a8a8;"
    "border-radius: 10px;"
"}"
"input[type=range]::-ms-thumb {"
    "border: none;"
    "height: 16px;"
    "width: 30px;"
    "border-radius: 50%;"
    "background: #990033;"
"}"
"input[type=range]:focus::-ms-fill-lower {"
    "background: #a2a2a2;"
"}"
"input[type=range]:focus::-ms-fill-upper {"
    "background: #a2a2a2;"
"}"
"</style>"
"<script type=\"text/javascript\">\r\n"
     "function sendCheckbox(Pin, cb) {"
        "document.getElementById(\"description\").innerHTML = \"Processing Checkbox\";\r\n"
        "if(cb.checked){"
        "server = \"checkbox/\" + Pin + \"/1\";\r\n"
        "}else{"
        "server = \"checkbox/\" + Pin + \"/0\";}\r\n"
        "request = new XMLHttpRequest();\r\n"
        "request.open(\"GET\", server, true);\r\n"
        "request.send(null);\r\n"
        "document.getElementById(\"description\").innerHTML = \"Processing Checkbox complete\";\r\n"
    "}\r\n"
    "function sendbutton(Pin,action){\r\n"
        "document.getElementById(\"description\").innerHTML = \"Processing Button\" + Pin + \" \" + action + \" Click\";\r\n"
        "server = \"button/\" + Pin + \"/\" + action;\r\n"
        "request = new XMLHttpRequest();\r\n"
        "request.open(\"GET\", server, true);\r\n"
        "request.send(null);\r\n"
    "}\r\n"
    "function sendSlider(Pin,value){\r\n"
        "ValNum = \"valueSlider\" + Pin;\r\n"
        "document.getElementById(ValNum).innerHTML=value;\r\n"
        "document.getElementById(\"description\").innerHTML = \"Processing Slider\";\r\n"
        "server = \"slider/\" + Pin + \"/\" + value;\r\n"
        "request = new XMLHttpRequest();\r\n"
        "request.open(\"GET\", server, true);\r\n"
        "request.send(null);\r\n"
    "}\r\n"
"</script>\r\n"
"</head>\r\n"
"<font face=\"Arial\">\r\n"
"<h1>Roboterhand MANU</h1>"
"<table>\r\n"
"<tr> <th>Fingersteuerung</th></tr>\r\n"
"<tr>"
  "<td>Daumen</td>"
  "<td>"
  "<button style= \"width:110px\" onclick=\"sendbutton(0,1);\"/>EIN</button>"
  "</td>"
  "<td>"
  "<button style= \"width:110px\" onclick=\"sendbutton(0,0);\"/>AUS</button>"
  "</td>"
"</tr>"
"<tr>"
  "<td>Zeigefinger</td>"
  "<td>"
  "<button style= \"width:110px\" onclick=\"sendbutton(1,1);\"/>EIN</button>"
  "</td>"
  "<td>"
  "<button style= \"width:110px\" onclick=\"sendbutton(1,0);\"/>AUS</button>"
  "</td>"
"</tr>"
"<tr>"
  "<td>Mittelfinger</td>"
  "<td>"
  "<button style=   \"width:110px\" onclick=\"sendbutton(2,1);\"/>EIN</button>"
  "</td>"
  "<td>"
  "<button style= \"width:110px\" onclick=\"sendbutton(2,0);\"/>AUS</button>"
  "</td>"
"</tr>"
"<tr>"
  "<td>Ringfinger</td>"
  "<td>"
  "<button style= \"width:110px\" onclick=\"sendbutton(3,1);\"/>EIN</button>"
  "</td>"
  "<td>"
  "<button style= \"width:110px\" onclick=\"sendbutton(3,0);\"/>AUS</button>"
  "</td>"
"</tr>"
"<tr>"
  "<td>Kleiner Finger</td>"
  "<td>"
  "<button style= \"width:110px\" onclick=\"sendbutton(4,1);\"/>EIN</button>"
  "</td>"
  "<td>"
  "<button style= \"width:110px\" onclick=\"sendbutton(4,0);\"/>AUS</button>"
  "</td>"
"</tr>"
"</table>\r\n"
"<table>\r\n"
"<tr> <th align=\"left\">Handgelenk</th></tr>\r\n"
"<tr>"
"<td>"
"<input type=\"range\" style=\"width:250px; height: 30px;\" id=\"slider1\" min=\"0\" max=\"100\" value=\"50\" step=\"1\" onchange=\"sendSlider(1, this.value);\"/>"
"</td>"
"<td>"
"<span id=\"valueSlider1\">50</span>\r\n"
"</td>"
"</table>\r\n"
"<table>\r\n"
"<tr> <th>LED-Streifen</th></tr>\r\n"
"<tr>\r\n"
"<td>ROT</td>"
"<td>"
"<div class=\"toggle\">"
"    <label>"
"    <input type=\"checkbox\" onclick=\"sendCheckbox(0,this);\"> <span class=\"slider\"></span>"
"    </label>"
"</div>"
"</td>"
"</tr>\r\n"
"<tr>\r\n"
"<td>GRUEN</td>"
"<td>"
"<div class=\"toggle\">"
"    <label>"
"    <input type=\"checkbox\" onclick=\"sendCheckbox(1,this);\"> <span class=\"slider\"></span>"
"    </label>"
"</div>"
"</td>"
"</tr>\r\n"
"<tr>\r\n"
"<td>BLAU</td>"
"<td>"
"<div class=\"toggle\">"
"    <label>"
"    <input type=\"checkbox\" onclick=\"sendCheckbox(2,this);\"> <span class=\"slider\"></span>"
"    </label>"
"</div>"
"</td>"
"</tr>\r\n"
"</table>\r\n"
"<br><br>\r\n"
"<br><br>\r\n"
"<p id=\"description\"> - </p>\r\n"
"</font>\r\n"
"</html>\r\n";

#endif

// "<td>"
//"<input type=\"range\" style=\"width: 90px; height: 30px;\" id=\"slider2\" min=\"0\" max=\"1\" value=\"0\" step=\"1\" onchange=\"sendSlider(1, this.value);\"/>\r\n"
//"</td>"
//"<td><span id=\"valueSlider1\">0</span></td>\r\n"
